name: "Test Actions"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  github_token: "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"
  
jobs:
  print:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "PAT is ${{env.github_token}}"
     
